/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ConstructionPayloadsRequest is the request to `/construction/payloads`. It contains the network, a slice of operations, and arbitrary metadata that was returned by the call to `/construction/metadata`. Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
type ConstructionPayloadsRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`

	Operations []Operation `json:"operations"`

	Metadata *interface{} `json:"metadata,omitempty"`

	PublicKeys []PublicKey `json:"public_keys,omitempty"`
}
