/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ConstructionDeriveRequest is passed to the `/construction/derive` endpoint. Network is provided in the request because some blockchains have different address formats for different networks. Metadata is provided in the request because some blockchains allow for multiple address types (i.e. different address for validators vs normal accounts).
type ConstructionDeriveRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`

	PublicKey *PublicKey `json:"public_key"`

	Metadata *interface{} `json:"metadata,omitempty"`
}
