/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// EventsBlocksResponse contains an ordered collection of BlockEvents and the max retrievable sequence.
type EventsBlocksResponse struct {
	// max_sequence is the maximum available sequence number to fetch.
	MaxSequence int64 `json:"max_sequence"`
	// events is an array of BlockEvents indicating the order to add and remove blocks to maintain a canonical view of blockchain state. Lightweight clients can use this event stream to update state without implementing their own block syncing logic.
	Events []BlockEvent `json:"events"`
}
