/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A NetworkRequest is utilized to retrieve some data specific exclusively to a NetworkIdentifier.
type NetworkRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`

	Metadata *interface{} `json:"metadata,omitempty"`
}
