/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A BlockTransactionRequest is used to fetch a Transaction included in a block that is not returned in a BlockResponse.
type BlockTransactionRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`

	BlockIdentifier *BlockIdentifier `json:"block_identifier"`

	TransactionIdentifier *TransactionIdentifier `json:"transaction_identifier"`
}
