/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A MempoolTransactionRequest is utilized to retrieve a transaction from the mempool.
type MempoolTransactionRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`

	TransactionIdentifier *TransactionIdentifier `json:"transaction_identifier"`
}
