/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// BlockEvent represents the addition or removal of a BlockIdentifier from storage. Streaming BlockEvents allows lightweight clients to update their own state without needing to implement their own syncing logic.
type BlockEvent struct {
	// sequence is the unique identifier of a BlockEvent within the context of a NetworkIdentifier.
	Sequence int64 `json:"sequence"`

	BlockIdentifier *BlockIdentifier `json:"block_identifier"`

	Type_ *BlockEventType `json:"type"`
}
