/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// TransactionIdentifierResponse contains the transaction_identifier of a transaction that was submitted to either `/construction/hash` or `/construction/submit`.
type TransactionIdentifierResponse struct {

	TransactionIdentifier *TransactionIdentifier `json:"transaction_identifier"`

	Metadata *interface{} `json:"metadata,omitempty"`
}
