/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// BlockTransaction contains a populated Transaction and the BlockIdentifier that contains it.
type BlockTransaction struct {

	BlockIdentifier *BlockIdentifier `json:"block_identifier"`

	Transaction *Transaction `json:"transaction"`
}
