/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// NetworkOptionsResponse contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.
type NetworkOptionsResponse struct {

	Version *Version `json:"version"`

	Allow *Allow `json:"allow"`
}
