/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// BlockEventType : BlockEventType determines if a BlockEvent represents the addition or removal of a block.
type BlockEventType string

// List of BlockEventType
const (
	ADDED BlockEventType = "block_added"
	REMOVED BlockEventType = "block_removed"
)
