/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Operator : Operator is used by query-related endpoints to determine how to apply conditions. If this field is not populated, the default `and` value will be used.
type Operator string

// List of Operator
const (
	OR Operator = "or"
	AND Operator = "and"
)
