/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ConstructionCombineRequest is the input to the `/construction/combine` endpoint. It contains the unsigned transaction blob returned by `/construction/payloads` and all required signatures to create a network transaction.
type ConstructionCombineRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`

	UnsignedTransaction string `json:"unsigned_transaction"`

	Signatures []Signature `json:"signatures"`
}
