/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CallRequest is the input to the `/call` endpoint.
type CallRequest struct {

	NetworkIdentifier *NetworkIdentifier `json:"network_identifier"`
	// Method is some network-specific procedure call. This method could map to a network-specific RPC endpoint, a method in an SDK generated from a smart contract, or some hybrid of the two. The implementation must define all available methods in the Allow object. However, it is up to the caller to determine which parameters to provide when invoking `/call`.
	Method string `json:"method"`
	// Parameters is some network-specific argument for a method. It is up to the caller to determine which parameters to provide when invoking `/call`.
	Parameters *interface{} `json:"parameters"`
}
