/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Signature contains the payload that was signed, the public keys of the keypairs used to produce the signature, the signature (encoded in hex), and the SignatureType. PublicKey is often times not known during construction of the signing payloads but may be needed to combine signatures properly.
type Signature struct {

	SigningPayload *SigningPayload `json:"signing_payload"`

	PublicKey *PublicKey `json:"public_key"`

	SignatureType *SignatureType `json:"signature_type"`

	HexBytes string `json:"hex_bytes"`
}
