/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to `/construction/preprocess` and `/construction/payloads`.
type ConstructionParseResponse struct {

	Operations []Operation `json:"operations"`
	// [DEPRECATED by `account_identifier_signers` in `v1.4.4`] All signers (addresses) of a particular transaction. If the transaction is unsigned, it should be empty.
	Signers []string `json:"signers,omitempty"`

	AccountIdentifierSigners []AccountIdentifier `json:"account_identifier_signers,omitempty"`

	Metadata *interface{} `json:"metadata,omitempty"`
}
