/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A MetadataRequest is utilized in any request where the only argument is optional metadata.
type MetadataRequest struct {

	Metadata *interface{} `json:"metadata,omitempty"`
}
