/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Amount is some Value of a Currency. It is considered invalid to specify a Value without a Currency.
type Amount struct {
	// Value of the transaction in atomic units represented as an arbitrary-sized signed integer. For example, 1 BTC would be represented by a value of 100000000.
	Value string `json:"value"`

	Currency *Currency `json:"currency"`

	Metadata *interface{} `json:"metadata,omitempty"`
}
