/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Coin contains its unique identifier and the amount it represents.
type Coin struct {

	CoinIdentifier *CoinIdentifier `json:"coin_identifier"`

	Amount *Amount `json:"amount"`
}
