/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SigningPayload is signed by the client with the keypair associated with an AccountIdentifier using the specified SignatureType. SignatureType can be optionally populated if there is a restriction on the signature scheme that can be used to sign the payload.
type SigningPayload struct {
	// [DEPRECATED by `account_identifier` in `v1.4.4`] The network-specific address of the account that should sign the payload.
	Address string `json:"address,omitempty"`

	AccountIdentifier *AccountIdentifier `json:"account_identifier,omitempty"`

	HexBytes string `json:"hex_bytes"`

	SignatureType *SignatureType `json:"signature_type,omitempty"`
}
