/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A BlockTransactionResponse contains information about a block transaction.
type BlockTransactionResponse struct {

	Transaction *Transaction `json:"transaction"`
}
