/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The block_identifier uniquely identifies a block in a particular network.
type BlockIdentifier struct {
	// This is also known as the block height.
	Index int64 `json:"index"`

	Hash string `json:"hash"`
}
