/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * API version: 1.4.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AccountBalance",
		strings.ToUpper("Post"),
		"/account/balance",
		AccountBalance,
	},

	Route{
		"AccountCoins",
		strings.ToUpper("Post"),
		"/account/coins",
		AccountCoins,
	},

	Route{
		"Block",
		strings.ToUpper("Post"),
		"/block",
		Block,
	},

	Route{
		"BlockTransaction",
		strings.ToUpper("Post"),
		"/block/transaction",
		BlockTransaction,
	},

	Route{
		"Call",
		strings.ToUpper("Post"),
		"/call",
		Call,
	},

	Route{
		"ConstructionCombine",
		strings.ToUpper("Post"),
		"/construction/combine",
		ConstructionCombine,
	},

	Route{
		"ConstructionDerive",
		strings.ToUpper("Post"),
		"/construction/derive",
		ConstructionDerive,
	},

	Route{
		"ConstructionHash",
		strings.ToUpper("Post"),
		"/construction/hash",
		ConstructionHash,
	},

	Route{
		"ConstructionMetadata",
		strings.ToUpper("Post"),
		"/construction/metadata",
		ConstructionMetadata,
	},

	Route{
		"ConstructionParse",
		strings.ToUpper("Post"),
		"/construction/parse",
		ConstructionParse,
	},

	Route{
		"ConstructionPayloads",
		strings.ToUpper("Post"),
		"/construction/payloads",
		ConstructionPayloads,
	},

	Route{
		"ConstructionPreprocess",
		strings.ToUpper("Post"),
		"/construction/preprocess",
		ConstructionPreprocess,
	},

	Route{
		"ConstructionSubmit",
		strings.ToUpper("Post"),
		"/construction/submit",
		ConstructionSubmit,
	},

	Route{
		"EventsBlocks",
		strings.ToUpper("Post"),
		"/events/blocks",
		EventsBlocks,
	},

	Route{
		"Mempool",
		strings.ToUpper("Post"),
		"/mempool",
		Mempool,
	},

	Route{
		"MempoolTransaction",
		strings.ToUpper("Post"),
		"/mempool/transaction",
		MempoolTransaction,
	},

	Route{
		"NetworkList",
		strings.ToUpper("Post"),
		"/network/list",
		NetworkList,
	},

	Route{
		"NetworkOptions",
		strings.ToUpper("Post"),
		"/network/options",
		NetworkOptions,
	},

	Route{
		"NetworkStatus",
		strings.ToUpper("Post"),
		"/network/status",
		NetworkStatus,
	},

	Route{
		"SearchTransactions",
		strings.ToUpper("Post"),
		"/search/transactions",
		SearchTransactions,
	},
}
